<?php

namespace common\components;

use common\models\Settings;
use yii\base\Component;

class GlobalProperty extends Component
{
    /**
     * @var $name string
     */
    public string $name = 'LocalMart';

    /**
     * @var $email_host string
     */
    public string $email_host = '';

    /**
     * @var $email_username string
     */
    public string $email_username = '';

    /**
     * @var $email_password string
     */
    public string $email_password = '';

    /**
     * @var $email_port string
     */
    public string $email_port = '';

    /**
     * @var $email_encryption string
     */
    public string $email_encryption = '';

    /**
     * @var $twilio_account_sid string
     */
    public string $twilio_account_sid = '';

    /**
     * @var $twilio_auth_token string
     */
    public string $twilio_auth_token = '';

    /**
     * @var $twilio_service_sid string
     */
    public string $twilio_service_sid = '';

    /**
     * @var $twilio_phone_number string
     */
    public string $twilio_phone_number = '';

    /**
     * @var $logo_dark string
     */
    public string $logo_dark = '';

    /**
     * @var $logo_light string
     */
    public string $logo_light = '';

    /**
     * @var $logo_transparent string
     */
    public string $logo_transparent = '';

    /**
     * @var $favicon string
     */
    public string $favicon = '';

    public function init()
    {
        $settings = Settings::findOne(1);
        if ($settings) {
            $this->name = $settings->app_name;
            $this->email_host = $settings->email_host;
            $this->email_username = $settings->email_username;
            $this->email_password = $settings->email_password;
            $this->email_port = $settings->email_port;
            $this->email_encryption = $settings->email_encryption;
            $this->twilio_account_sid = $settings->twilio_account_sid;
            $this->twilio_auth_token = $settings->twilio_auth_token;
            $this->twilio_service_sid = $settings->twilio_service_sid;
            $this->twilio_phone_number = $settings->twilio_phone_number;
            $this->logo_dark = $settings->getImage('logo_dark','','frontend-logo-image');
            $this->logo_light = $settings->getImage('logo_light','','frontend-logo-image');
            $this->logo_transparent = $settings->getImage('logo_transparent','','frontend-logo-image');
            $this->favicon = $settings->getImage('favicon','','frontend-logo-image');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

}