<?php

namespace frontend\modules\seller;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'frontend\modules\seller\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public $defaultRoute = 'site/index';
}